
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../utils/supabase-custom';

const SUPABASE_URL = "https://bgcegarmliqfvimmsupq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnY2VnYXJtbGlxZnZpbW1zdXBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyOTU4MTcsImV4cCI6MjA2Mjg3MTgxN30.3NU-T9sIWAZaS_Kr2ivGmVnCZVAlY6RSedJpDylX12Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: {
    schema: 'public',
  },
});
